[package]
name = "remark-proto"
version = "0.1.0"
authors = ["Dmytro Lysai <d@emphased.net>"]
license = "Apache-2.0"
edition = "2018"
build = "build.rs"

[dependencies]
bytes = "0.4"
prost = "0.4"
prost-derive = "0.4"

[build-dependencies]
prost-build = "0.4"
